name: Release & Container Publish

on:
  push:
    branches:
      - main
  release:
    types: [published] # ← リリースが公開されたタイミングで発火

jobs:
  release-please:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7
        with:
          config-file: .github/repo/release-please-config.json
          manifest-file: .github/repo/.release-please-manifest.json

  build-and-push-container-base:
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && startsWith(github.event.release.tag_name, 'container-base.v')
    permissions:
      contents: write
      packages: write

    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v4

      - name: バージョンの抽出
        id: prep
        run: |
          TAG="${{ github.event.release.tag_name }}" # 例: container-base.v0.1.0
          VERSION="${TAG#container-base.v}" # 例: 0.1.0
          IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/container-base"
          
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "image=$IMAGE_NAME" >> $GITHUB_OUTPUT
