name: Reusable Sync Templates Workflow

on:
  workflow_call:
    inputs:
      boilerplate-repository:
        description: '取得対象の Boilerplate リポジトリ (AUTO の場合は自動判別)'
        type: string
        required: false
        default: 'AUTO'
      common-repository:
        description: '取得対象の Common リポジトリ'
        type: string
        required: false
        default: 'mon2org/Common'
      pr-branch:
        description: '作成する PR のブランチ名'
        type: string
        required: false
        default: 'chore/sync-templates'
      pr-title:
        description: '作成する PR のタイトル'
        type: string
        required: false
        default: 'chore: テンプレートの最新化'
      pr-commit-message:
        description: 'コミットメッセージ'
        type: string
        required: false
        default: 'chore: テンプレートの最新化'
    secrets:
      token:
        description: 'リポジトリ取得および PR 作成用 GitHub Token'
        required: false

jobs:
  sync-templates:
    uses: mon2org/Common/.github/workflows/core.yml@main
    with:
      # mise タスク経由で同期処理を実行（または uses-action: ./.github/actions/update/sync-templates の指定も可能）
      run-command: mise run sync-templates --boilerplate "${{ inputs.boilerplate-repository }}" --common "${{ inputs.common-repository }}"
      create-pr: true
      pr-branch: ${{ inputs.pr-branch }}
      pr-title: ${{ inputs.pr-title }}
    secrets: inherit
